//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_Student.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Open_Subjects
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Open_Subjects()
        {
            this.Register_Subjects = new HashSet<Register_Subjects>();
        }
    
        public int Sub_id { get; set; }
        public string Sub_Name { get; set; }
        public Nullable<int> Sub_unit { get; set; }
        public string Teacher_id { get; set; }
    
        public virtual ProfileTeacher ProfileTeacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Register_Subjects> Register_Subjects { get; set; }
    }
}
