//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_Student.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Open_Subjects> Open_Subjects { get; set; }
        public virtual DbSet<PreName> PreName { get; set; }
        public virtual DbSet<ProfileStudent> ProfileStudent { get; set; }
        public virtual DbSet<ProfileTeacher> ProfileTeacher { get; set; }
        public virtual DbSet<Register_Subjects> Register_Subjects { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<ViewOpenSub> ViewOpenSub { get; set; }
        public virtual DbSet<ViewReport> ViewReport { get; set; }
        public virtual DbSet<ViewStud> ViewStud { get; set; }
        public virtual DbSet<ViewTeacher> ViewTeacher { get; set; }
    }
}
