//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_Student.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Register_Subjects
    {
        public int id { get; set; }
        public string Stud_id { get; set; }
        public Nullable<int> Sub_id { get; set; }
        public string Grad { get; set; }
    
        public virtual Open_Subjects Open_Subjects { get; set; }
        public virtual ProfileStudent ProfileStudent { get; set; }
    }
}
