//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_Student.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewOpenSub
    {
        public int Sub_id { get; set; }
        public string Sub_Name { get; set; }
        public Nullable<int> Sub_unit { get; set; }
        public string FristName { get; set; }
        public string LastName { get; set; }
    }
}
