//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_Student.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewStud
    {
        public string Stud_id { get; set; }
        public Nullable<int> Pre_Name { get; set; }
        public string FristName { get; set; }
        public string LastName { get; set; }
        public string Group_id { get; set; }
        public string Branch { get; set; }
        public string Faculty { get; set; }
        public string Expr1 { get; set; }
    }
}
